### ISSUE TITLE
Syntax error on ldi instruction

### ISSUE THREAD

**Issue by mojobojo** [bentley/rgbds#73]
I have a disassembly that uses the instruction 

```
ldi  a,[hl]
```

rgbasm tells me

```
rgbasm -i src/ -o src/main.o src/main.asm
ERROR:  src/main.asm(1644) :
        syntax error
C:\MinGW\msys\1.0\bin\rgbasm.exe: Assembly aborted in pass 1 (1 errors)!
make: *** [src/main.o] Error 1
```

Right now I am working past that by doing

```
db $2A ; ldi  a,[hl]
```

**Comment by bentley** [comment]
This instruction is called `ld a,[hli]` in rgbds.

It would probably be a good idea to support the alternate syntax though, so I’ll leave this open.

**Comment by mojobojo** [comment]
I see, that explains it. Thank you.

**Comment by Ben10do** [comment]
Sorry for bumping such an old issue, but I wanted to look into resolving this.

In addition to the standard syntax (e.g. `ld a, [hl+]`, `ld a, [hli]`, etc), it seems like rgbds has for a long time (as far as the Git blame goes back to) also supported `ldi [hl], a`, but confusingly, the other direction is `ldi a, hl`, not the expected `ldi a, [hl]` (`ldi hl, a` is _not_ supported; also, all of these similarly apply to decrementing `hl` as well).

The extra syntax requested above should be quite easy to add, but should the older (non-bracketed) syntax still remain? It's inconsistent, but as it's been in rgbds for a while, there's the potential for some code to rely on it.

**Comment by AntonioND** [comment]
Well, most projects that rely on such an old syntax are most likely broken. I say let's remove all weird sintaxes like that one. Another example is `jp [hl]` instead of the correct `jp hl`. It confuses people, and there are no real benefits. For starters, every single project that is more than ~5 years old will rely on linkfiles, so you still have to modify a few things to make them work, why not fix the incorrect syntax of a few lines while you are at it?

**Comment by Ben10do** [comment]
If we do go down that route, we could either:
- Make such instructions obsolete, such that the assembler produces a specific error (e.g. `'ldi hl, a' is obsolete. Use 'ldi [hl], a' or 'ld [hl+], a' instead.`).
- Completely remove them (resulting in the standard `Syntax error` message).

Thoughts? (In addition to the above)

**Comment by AntonioND** [comment]
I think that the parser is a potentially problematic part of the code and, the simpler it is, the better. A syntax error seems perfectly fine to me, there's no point in making syntaxes obsolete if we aren't going to drop them at some point in the future...

**Comment by bentley** [comment]
> Well, most projects that rely on such an old syntax are most likely broken. … Another example is jp [hl] instead of the correct jp hl. It confuses people, and there are no real benefits.

`jp [hl]` may be illogical but it has been that way since time immemorial; take a look at any random assortment of Z80 manuals and you’ll see it all over the place. It makes sense to add support for the logical alternative, but I don’t see any value in making common instructions like that syntax errors.

Having alternate instruction syntaxes is basically zero maintenance (e.g., de269987f75dbf32fe8ddca5ef7501b809f7ed45). The complexity in the parser is in other places.

**Comment by Ben10do** [comment]
Thanks for your input, @bentley. Just to clarify, does that mean you'd rather take a similar approach with `ldi a, hl` (of adding the logical syntax, in addition to the established but illogical syntax)?

**Comment by bentley** [comment]
Yes.
